### ISSUE TITLE
大佬，QQREAD_COOKIE是什么格式的，能发个例子吗

### ISSUE THREAD

**Issue by wangning6666** [Lexho1/qqread_Actions#2]

**Comment by Lexho1** [comment]
xxx@xxx@xxx@（换行可以加账号2 以此类推）
双账号示例：xxx@xxx@xxx@（换行）
xxx@xxx@xxx

**Comment by wangning6666** [comment]
我抓取到的cookie是  ywguid=********;ywkey=**********;platform=ios;channel=****; 类似这样的，都需要填写那些，请大佬指点一下

**Comment by Lexho1** [comment]
全部为一个cookie 你别拆分他 
{"ywsession":"pc2q13c8hpoz72mxa3yz3n578s7eg1mg","Cookie":"ywguid=1908320074;ywkey=ywpnIUPYwBFy;platform=ios;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0;platform=ios;openid=44B8A251918718DD4AF4F841F13682DA","Connection":"keep-alive","Content-Type":"application/json","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.30.0/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip, deflate, br","mpversion":"0.30.0"}
这样是其中一个cookie的格式

**Comment by wangning6666** [comment]
{"Host":"mqqapi.reader.qq.com","Accept":"/","Content-Type":"application/json","ywsession":"rjd08wat1iy0vo4mdb52jpeuw6rg0eg5","User-Agent":"QQ/8.4.17.638 CFNetwork/1128.0.1 Darwin/19.6.0","Connection":"keep-alive","Cookie":"ywguid=13938XX938;ywkey=ywln21rIrFz9S;platform=ios;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.17;os_ver=iOS 13.7;mpos_ver=1.21.0;platform=ios;openid=4AAF5AA22955C46843AA161752661A33","Accept-Language":"zh-cn","mpversion":"0.30.0","Referer":"https://appservice.qq.com/1110657249/0.30.0/page-frame.html","Accept-Encoding":"gzip, deflate, br"}
大佬，直接把这个复制进去不好使啊？

**Comment by Lexho1** [comment]
不是这个格式的 你获取错了吧 这个是企鹅读书 qq小程序来的

**Comment by wangning6666** [comment]
我就是抓的企鹅读书小程序，user/init和addreadtimewithbid都试过了，两个都不好使
